package org.newit.microservice.ebusiness.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.newit.microservice.ebusiness.model.Item;
import org.newit.microservice.ebusiness.model.ItemExample;

public interface ItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Jun 06 16:04:54 CST 2019
     */
    long countByExample(ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Jun 06 16:04:54 CST 2019
     */
    int deleteByExample(ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Jun 06 16:04:54 CST 2019
     */
    int insert(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Jun 06 16:04:54 CST 2019
     */
    int insertSelective(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Jun 06 16:04:54 CST 2019
     */
    List<Item> selectByExample(ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Jun 06 16:04:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") Item record, @Param("example") ItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Jun 06 16:04:54 CST 2019
     */
    int updateByExample(@Param("record") Item record, @Param("example") ItemExample example);
}