server:
  port: 8888

spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/newitstudy/spring-cloud-config
          username: newitstudy
          password: microservice2019