package org.newit.microservice.databasedemo.model.newit;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newit..user.id
     *
     * @mbg.generated Tue Jun 04 14:12:04 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newit..user.name
     *
     * @mbg.generated Tue Jun 04 14:12:04 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newit..user.password
     *
     * @mbg.generated Tue Jun 04 14:12:04 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newit..user.created_time
     *
     * @mbg.generated Tue Jun 04 14:12:04 CST 2019
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newit..user.updated_time
     *
     * @mbg.generated Tue Jun 04 14:12:04 CST 2019
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newit..user.id
     *
     * @return the value of newit..user.id
     *
     * @mbg.generated Tue Jun 04 14:12:04 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newit..user.id
     *
     * @param id the value for newit..user.id
     *
     * @mbg.generated Tue Jun 04 14:12:04 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newit..user.name
     *
     * @return the value of newit..user.name
     *
     * @mbg.generated Tue Jun 04 14:12:04 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newit..user.name
     *
     * @param name the value for newit..user.name
     *
     * @mbg.generated Tue Jun 04 14:12:04 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newit..user.password
     *
     * @return the value of newit..user.password
     *
     * @mbg.generated Tue Jun 04 14:12:04 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newit..user.password
     *
     * @param password the value for newit..user.password
     *
     * @mbg.generated Tue Jun 04 14:12:04 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newit..user.created_time
     *
     * @return the value of newit..user.created_time
     *
     * @mbg.generated Tue Jun 04 14:12:04 CST 2019
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newit..user.created_time
     *
     * @param createdTime the value for newit..user.created_time
     *
     * @mbg.generated Tue Jun 04 14:12:04 CST 2019
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newit..user.updated_time
     *
     * @return the value of newit..user.updated_time
     *
     * @mbg.generated Tue Jun 04 14:12:04 CST 2019
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newit..user.updated_time
     *
     * @param updatedTime the value for newit..user.updated_time
     *
     * @mbg.generated Tue Jun 04 14:12:04 CST 2019
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}